service: mtgml-global-database

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  globalDecksTable: global-decks
  globalCardsTable: global-cards

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      convertEmptyValues: true
      migrate: true

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

resources:
  # DynamoDB Tables
  - ${file(resources/dynamodb-tables.yml)}
