Resources:
  PricesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.pricesBucket}
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
            Effect: Allow
            Resource:
              - "*"
            Principal:
              - "*"
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000

# Print out the name of the bucket that is created
Outputs:
  PricesBucketArn:
    Value:
       Fn::GetAtt:
        - PricesBucket
        - Arn
    Export:
      Name: PricesBucketArn

  PricesBucketName:
    Value:
      Ref: PricesBucket
    Export:
      Name: PricesBucket
